language: node_js
node_js: '12'
cache: npm
jobs:
  include:
    - stage: Bootstrap
      script:
        - npm run build
      artifacts:
        paths:
          - "*/dist"
          - "*/lib"
          - "*/types"
        expire_in: 1 day

    - stage: Produce Coverage
      node_js: '12'
      script:
        - npm run test:coverage