language: node_js
node_js: '12'
cache: npm
jobs:
  include:
    - stage: test
      script:
        - npm run build
        - npm run test:coverage
        - npm run report:coverage
      artifacts:
        paths:
          - "*/dist"
          - "*/lib"
          - "*/types"
        expire_in: 1 day